version: '3.8'

services:
    frontend:
        build:
            context: ./frontend
        container_name: frontend
        ports:
            - '3000:3000'
        env_file:
            - ./frontend/.env.local
        restart: unless-stopped
        networks:
            - app-network
        depends_on:
            - backend

    backend:
        build:
            context: ./backend
        container_name: backend
        ports:
            - '8080:8080'
        env_file:
            - ./backend/.env
        environment:
            DATABASE_URL: postgres://postgres:123456@postgres:5432/db
        restart: unless-stopped
        networks:
            - app-network
        depends_on:
            - postgres

    postgres:
        image: postgres:16
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: db
        ports:
            - '5432:5432'
        restart: always
        networks:
            - app-network
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:

networks:
    app-network:
        driver: bridge
