version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:123456@db:5432/db
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
